# Site settings
title: Raketebar
email: info@raketebar.ch
url: https://www.raketebar.ch
description: "Raketabar Description"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00acef'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https//www.facebook.com/raketebar
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/matmenzl/raketebar

# Build settings
markdown: kramdown
permalink: pretty
